version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: resturant_backend
    ports:
      - "5001:8080"        # Host:Container
    volumes:
      - ./Backend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node server.js

  frontend:
    build:
      context: ./Frontend
    container_name: resturant_frontend
    ports:
      - "3000:5173"        # Host:Container (Vite default is 5173)
    volumes:
      - ./Frontend:/app
    command: npm run dev -- --host
